// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plexxis_Mobile_FullStack_JS_CRUD_Exercise.Models;

namespace Plexxis_Mobile_FullStack_JS_CRUD_Exercise.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20190825030256_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");
#pragma warning restore 612, 618
        }
    }
}
