// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plexxis_Mobile_FullStack_JS_CRUD_Exercise.Models;

namespace Plexxis_Mobile_FullStack_JS_CRUD_Exercise.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20190825033820_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Plexxis_Mobile_FullStack_JS_CRUD_Exercise.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("assigned");

                    b.Property<string>("branch");

                    b.Property<string>("city");

                    b.Property<string>("code");

                    b.Property<string>("color");

                    b.Property<string>("name");

                    b.Property<string>("profession");

                    b.HasKey("id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
